### ISSUE TITLE
1. Introduction. Write a one paragraph summary/introduction of your term project.

### ISSUE THREAD

**Issue by conneroisu** [conneroisu/sfhw-proj2#103]
<sub><a href="https://huly.app/guest/cpre381?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU2MTI3NzFlMDYzMmRkMDhlMjVmZjYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViY29ubmVyLWNwcmUzODEtNjcyNTBhMGUtNWMwM2NlOGY1Zi02YmU0NzMifQ.N0799bXorXNmi1B_9viNQD9NTCQekQggeeCTIGvXdhk">Huly&reg;: <b>PROJE-103</b></a></sub>

**Comment by DanielMauricio13** [comment]
Building on the single-cycle processor created earlier in the semester, the goal of this term's project is to design, implement, and test a pipelined MIPS processor. The main goal is to use instruction pipelining, a crucial idea in contemporary CPU architecture, to build a high-performance processor. Instruction Fetch (IF), Instruction Decode/Register Fetch (ID), Execute (EX), Memory Access (MEM), and Write-Back (WB) are the five phases that make up the pipeline. Because each stage is made to carry out a certain subset of duties, throughput can be increased by processing numerous instructions at once.

There are two stages to the project's implementation. Instruction hazards, including data, control, and structural hazards, are addressed in the first phase by carefully arranging instructions during program compilation in a software-scheduled pipeline. This method highlights the significance of instruction-level scheduling in preventing pipeline conflicts while offering a fundamental grasp of pipelining.

Hardware-based solutions are implemented in the second phase to manage dangers in a dynamic manner. Implementing hazard detecting units, forwarding (bypassing) logic to address data risks, and stalling methods to control hazards and manage load-use are all included in this. In order to reduce performance penalties brought on by control hazards, the control logic also manages branch prediction or branch resolution procedures during the ID stage. Additionally, by integrating memory operations, the EX/MEM stage enables the processor to manage data read and write activities with ease.

The end result of the research is a hardware-scheduled pipelined MIPS processor that can run any MIPS software that was initially intended for a single-cycle processor. Correctness is ensured by extensive testing, which includes functional verification for pipeline execution under a variety of hazards and performance benchmarks that show the processor's efficiency gains over the single-cycle architecture. The project offers a thorough examination of contemporary pipelined processor architecture by bridging theoretical ideas with real-world design and implementation through the synthesis of the pipeline for FPGA hardware.
