### ISSUE TITLE
7. Challenges

### ISSUE THREAD

**Issue by conneroisu** [conneroisu/sfhw-proj2#109]
7. Challenges. This term project was challenging for every group. In at least three detailed paragraphs, describe the three most critical challenges your group faced, how you resolved them, and how you could avoid them in the future.

<sub><a href="https://huly.app/guest/cpre381?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU2MTM2ZjFlMDYzMmRkMDhlMjYwNTMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViY29ubmVyLWNwcmUzODEtNjcyNTBhMGUtNWMwM2NlOGY1Zi02YmU0NzMifQ.PSGBRdeVnJ5IYlNXVPJ_Z58aXcL_2oaiKmt9KAx4pJA">Huly&reg;: <b>PROJE-109</b></a></sub>

**Comment by conneroisu** [comment]
Need ideas for this. Feel free to post them here.

**Comment by conneroisu** [comment]
Avoided Compiler errors by not duplicating code (Proj1 -> Proj2)

**Comment by conneroisu** [comment]
Finish this by thursday pls

**Comment by Kariniux** [comment]
Most errors I encountered with (most likely a group thing as well) were unbounded components in instantiation. This could be due to multiple files with the same name which leads the compiler to believe that the file name is incorrect from the one in the component section. Avoiding this by renaming files or double checking its instantiated correctly if changed.

**Comment by aidanfoss** [comment]
> Most errors I encountered with (most likely a group thing as well) were unbounded components in instantiation. This could be due to multiple files with the same name which leads the compiler to believe that the file name is incorrect from the one in the component section. Avoiding this by renaming files or double checking its instantiated correctly if changed.

this needs a rewrite
