### ISSUE TITLE
[2.b.iii] generalized list of potential data dependencies. From this generalized list, select those dependencies that can be forwarded (write down the corresponding pipeline stages that will be forwarding and receiving the data), and those dependencies that will require hazard stalls.

### ISSUE THREAD

**Issue by aidanfoss** [conneroisu/sfhw-proj2#15]

**Comment by conneroisu** [comment]
Generalized list of potential data dependencies:

1. Destination register in the MEM stage matches the `rs` or `rt` register in the **ID** stage.
2. `rs` or `rt` value in the ID stage matches the destination register in the **EX** stage.

Dependencies that can be forwarded:

1. Destination register in the MEM stage matches the rs or rt register in the **ID** stage:

   - Forwarding stages: **MEM** to **EX**
   - The data from the **MEM** stage can be forwarded to the EX stage to resolve the dependency.

2. `rs` or `rt` value in the ID stage matches the destination register in the **EX** stage:
   - Forwarding stages: EX to EX
   - The data from the EX stage can be forwarded to the EX stage of the dependent instruction.

Dependencies that require hazard stalls:

1. Destination register in the **MEM** stage matches the rs or rt register in the ID stage:

   - If the data is not available for forwarding from the MEM stage to the EX stage, a hazard stall is required.

2. `rs` or `rt` value in the ID stage matches the destination register in the EX stage:
   - If the data is not available for forwarding from the EX stage to the EX stage of the dependent instruction, a hazard stall is required.

Additional conditions for detecting data hazards:

- Check if the reg write signal is 1.
- Ensure that the matching registers condition is met.
- Verify that the destination register address is not 00000.

If all these conditions are satisfied, a data hazard is detected, and a stall is necessary.

Control hazards:

- If a branching or jump signal is on, a flush is required.
- Since the branching logic is in the decode stage, flushing is only needed in the ID stage.

**Comment by aidanfoss** [comment]
might be useful to work in the spreadsheet
#23 
https://docs.google.com/spreadsheets/d/1RUNOOiJ3DZ2heZ5_la7ENw52pGrtweVW7ax-dkXzsRU/edit?gid=504132693#gid=504132693

**Comment by Kariniux** [comment]
Generalized List of Data Dependencies for the Processor:
Load-Store: Data dependencies can come up when a store instruction comes right after a load instruction. The store instructions needs data to be loaded in the previous cycle. 
Immediate to Immediate: Dependencies can happen when the one immediate uses the result from the other. 
Register to Register to Register: Dependencies exist when multiple register-using instructions need the register results or use the same registers in different instructions.
Register to Register: Dependencies can exist between two register-using instructions.
Immediate to Register: Dependencies can come up when a immediate instruction writes to a register that a following register-using instructions will need the result.

**Comment by aidanfoss** [comment]
![image](https://github.com/user-attachments/assets/41c815fb-309d-4691-8b8d-4a4be68ba173)

@Kariniux
